name: Build and Test SwiftUI App

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    name: Build and Test
    runs-on: flyci-macos-14-m2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: xcodebuild build -scheme FlyCIiOSDemo -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15 Pro' -sdk iphonesimulator

      - name: Test
        run: xcodebuild build -scheme FlyCIiOSDemo -destination 'platform=iOS Simulator,OS=17.5,name=iPhone 15 Pro' -sdk iphonesimulator
